name: 🐞 Bug Report (v2)
description: Create a report to help us improve.
title: "[BUG]: "
labels: ["bug"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: dropdown
  attributes:
    label: Version
    description: What version are you using?
    multiple: false
    options:
      - label: v4.0.0 (Latest)
      - label: v3.3.0
      - label: v3.2.0
      - label: v3.1.0
      - label: v3.0.3
      - label: v3.0.2
      - label: v3.0.1
      - label: v3.0.0
      - label: v2.1.2
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe The Bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error...
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem.
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Platform
    description: |
      examples:
        - Desktop
        - Laptop
        - Smartphone
        - Tablet
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Device
    description: |
      examples:
        - Desktop
        - Dell Laptop
        - iPhone 6
        - Galaxy S9
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: OS
    description: |
      examples:
        - Windows 10
        - macOS 10.0
        - iOS 8.1
        - Android 12
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Browser
    description: |
      examples:
        - Chrome
        - Firefox
        - Safari
        - Smart Device Stock
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Browser Version
    description: |
      example:
        - 97.0.4692.99 (Official Build) (64-bit)
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false