name: 🐞 Bug Report
description: Create a report to help us improve.
title: "[BUG]: "
labels: ["bug"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: markdown
  attributes:
    value: "<hr>"
- type: dropdown
  attributes:
    label: Version
    description: What version are you using?
    multiple: false
    options: [
      "v4.0.0 (Latest)",
      "v3.3.0",
      "v3.2.0",
      "v3.1.0",
      "v3.0.3",
      "v3.0.2",
      "v3.0.1",
      "v3.0.0",
      "v2.1.2"
    ]
  validations:
    required: true
- type: markdown
  attributes:
    value: "<hr>"
- type: textarea
  attributes:
    label: Describe The Bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: markdown
  attributes:
    value: "<hr>"
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: markdown
  attributes:
    value: "<hr>"
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error...
  validations:
    required: true
- type: markdown
  attributes:
    value: "<hr>"
- type: textarea
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem.
  validations:
    required: false
- type: markdown
  attributes:
    value: "<hr>"
- type: input
  attributes:
    label: Platform
    description: |
      examples:
        - Desktop
        - Laptop
        - Smartphone
        - Tablet
  validations:
    required: true
- type: markdown
  attributes:
    value: "<hr>"
- type: input
  attributes:
    label: Device
    description: |
      examples:
        - Desktop
        - Dell Laptop
        - iPhone 6
        - Galaxy S9
  validations:
    required: true
- type: markdown
  attributes:
    value: "<hr>"
- type: input
  attributes:
    label: OS
    description: |
      examples:
        - Windows 10
        - macOS 10.0
        - iOS 8.1
        - Android 12
  validations:
    required: true
- type: markdown
  attributes:
    value: "<hr>"
- type: input
  attributes:
    label: Browser
    description: |
      examples:
        - Chrome
        - Firefox
        - Safari
        - Smart Device Stock
  validations:
    required: true
- type: markdown
  attributes:
    value: "<hr>"
- type: input
  attributes:
    label: Browser Version
    description: |
      example:
        - 97.0.4692.99 (Official Build) (64-bit)
  validations:
    required: true
- type: markdown
  attributes:
    value: "<hr>"
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: markdown
  attributes:
    value: "Thank you for filing a bug report!"